# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory
WORKDIR /frontend

# Install app dependencies
COPY package*.json ./
RUN npm install

# Ensure that webpack is globally installed and has executable permissions
RUN npm install -g webpack webpack-cli
RUN chmod +x /usr/local/bin/webpack

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Install http-server to serve the build directory
RUN npm install -g http-server

# Expose the port the app runs on
EXPOSE 80

# Define the command to run the app
CMD ["http-server", "build", "-p", "80"]