# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory
WORKDIR /frontend

# Install app dependencies
COPY package*.json ./
RUN npm install

# Install Webpack globally
RUN npm install -g webpack webpack-cli

# Copy the rest of the application code
COPY . .

# Build the application using Webpack
RUN webpack --config webpack.config.js

# Install http-server to serve the build directory
RUN npm install -g http-server

# Expose the port the app runs on
EXPOSE 80

# Define the command to run the app, serving the built directory
CMD ["http-server", "src/main/resources/static/built", "-p", "80"]
