name: Backend CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Maven
      run: sudo apt-get install -y maven

    - name: Build with Maven
      run: |
        cd backend
        mvn clean package

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create ECR repository if it doesn't exist
      run: |
        aws ecr describe-repositories --repository-names my-backend || aws ecr create-repository --repository-name my-backend

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push backend Docker image
      run: |
        cd backend
        docker build -t my-backend .
        docker tag my-backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-backend:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-backend:latest

    - name: Replace placeholders in ECS task definition
      run: |
        sed -i 's/ACCOUNT_ID/${{ secrets.AWS_ACCOUNT_ID }}/g' infrastructure/ecs-task-definition.json
        sed -i 's/REGION/${{ secrets.AWS_REGION }}/g' infrastructure/ecs-task-definition.json

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: infrastructure/ecs-task-definition.json
        service: my-backend-service
        cluster: my-cluster
        wait-for-service-stability: true
